# Generated by Django 5.2 on 2025-04-06 07:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bills",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill_name", models.CharField(max_length=100)),
                ("bill_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bill_currency",
                    models.CharField(
                        choices=[("idr", "IDR"), ("usd", "USD")], max_length=3
                    ),
                ),
                ("bill_reminder_date", models.DateField()),
                ("bill_reminder_time", models.TimeField()),
                ("payment_account", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
