# Generated by Django 5.2 on 2025-04-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bills",
            name="bill_reminder_time",
        ),
    ]
