# Generated by Django 5.2 on 2025-04-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_remove_bills_bill_reminder_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bills",
            name="bill_reminder_date",
        ),
        migrations.AddField(
            model_name="bills",
            name="payment_day",
            field=models.IntegerField(default=1),
        ),
    ]
