# Generated by Django 5.2 on 2025-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="paid_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
