# Generated by Django 5.2 on 2025-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_paid_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="paid_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
