# Generated by Django 5.2 on 2025-04-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_paid_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="due_time",
        ),
    ]
